### ISSUE TITLE
Restore service to Telegram <=> IRC bridges with teleirc

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#75]
# Summary

Restore service to the [teleirc](https://github.com/RITlug/teleirc) bot we used for Telegram <=> IRC bridges

# Background

Around Saturday, Nov. 24th, the virtual machine used for bridge bots in RITlug's infrastructure was wiped because of unanticipated issues with the VM. I expected the new automation to re-deploy the Telegram bots would be straightforward, but the unanticipated issues from teleirc's [v1.2.2 milestone](https://github.com/RITlug/teleirc/milestone/4) discovered breaking issues in our environment.

Once fixes are released upstream, our bots will again have clean deployments. As a side note, we will revisit our CI testing in Teleirc to prevent mistakes like this from happening again.

# Details

Once a new version is cut upstream, we can upgrade the existing bots by updating the `default_version` variable in the `teleirc` Ansible role found in [FOSSRIT/infrastructure](https://github.com/FOSSRIT/infrastructure). Knock on wood, it should be easy.

# Outcome

Telegram bridges are back online

**Comment by Tjzabel** [comment]
@jwflory I can talk to you now about this if you want.

**Comment by Tjzabel** [comment]
The issue appears to be due to the node version installed on the CentOS machine.

As I suspected, the issue looks to be due to the version of node (v6.14.3) CentOS installs. This version does not support async calls, which has been causing our issues. Node from EPEL.repo is not able to upgrade to the necessary node version teleirc needs. Shown below is the stacktrace:

```
/usr/lib64/teleirc/rit-foss/lib/TelegramHandlers/TgDocumentHandler.js:31
    async RelayDocumentMessage(from, document) {
          ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib64/teleirc/rit-foss/lib/TeleIrc.js:9:27)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib64/teleirc/rit-foss/teleirc.js:6:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```

**Comment by jwflory** [comment]
Telegram service is now restored ([_see post_](https://lists.fedoraproject.org/archives/list/fossrit@lists.fedorahosted.org/message/M43PQCNSZGQPFYKACHGH255VDJ42FR2I/)). Closing as complete. :clapper:
